services:
  meta_mkdocs_editor:
    image: filebrowser/filebrowser:s6
    container_name: meta_mkdocs_editor
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${PROJECTS}:/srv
      - ./settings.json:/config/settings.json
      - ./filebrowser.db:/database/filebrowser.db
    ports:
      - ${PORT_EDITOR}:80
    restart: unless-stopped
  meta_mkdocs:
    image: ghcr.io/ruanformigoni/meta-mkdocs:latest
    container_name: meta_mkdocs
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${PROJECTS}:/app/projects
    ports:
      - ${PORT_MAIN}:${PORT_MAIN}
      - ${PORT_SERVE}:${PORT_SERVE}
    command: /app/projects "${DOMAIN}" "${PORT_MAIN}" "${PORT_EDITOR}" "${PORT_SERVE}"
    restart: unless-stopped
