services:
  meta_mkdocs_editor:
    image: theia-ide
    container_name: meta_mkdocs_editor
    user: "1000:1000"
    ports:
      - ${PORT_EDITOR}:3000
    volumes:
      - ${PROJECTS}:/app/projects

  meta_mkdocs:
    image: ghcr.io/ruanformigoni/meta-mkdocs:latest
    container_name: meta_mkdocs
    environment:
      - PUID=1000
      - P{GID=1000
    volumes:
      - ${PROJECTS}:/app/projects
    ports:
      - ${PORT_MAIN}:${PORT_MAIN}
      - ${PORT_SERVE}:${PORT_SERVE}
    command: /app/projects "${DOMAIN}" "${PORT_MAIN}" "${PORT_EDITOR}" "${PORT_SERVE}"
    restart: unless-stopped
